container:
  image: gradle:jdk11

check_task:
  gradle_cache:
    fingerprint_script:
      - cat build.gradle.kts
    folder: ~/.gradle/caches
  check_script: ./gradlew check
  always:
    junit_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
