name: gradle
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Gradle Check
    steps:
      - uses: actions/checkout@v2
      - uses: cirruslabs/http-cache-action@master
      - uses: actions/setup-java@v1
      - run: ./gradlew check